### ISSUE TITLE
Backwards lifting of cmp-then-jhs branches

### ISSUE THREAD

**Issue by JJJollyjim** [joshwatson/binaryninja-msp430#11]
Consider this code (from MSP430x2xx Family User's Guide (Rev. J), section 3.4.6.24):

![2020-12-06-094115_752x125_scrot](https://user-images.githubusercontent.com/691552/101263013-3bf65e80-37a7-11eb-98dd-2881355ee531.png)

Disassembled, in binja, everything seems fine:

![2020-12-06-094059_999x435_scrot](https://user-images.githubusercontent.com/691552/101263038-60523b00-37a7-11eb-8667-c9ad6cfb6962.png)

But once lifted to LLIL, the operands of the `>=` are reversed!

![2020-12-06-094106_1077x391_scrot](https://user-images.githubusercontent.com/691552/101263052-8b3c8f00-37a7-11eb-89d3-c22330af00ed.png)

I'm not really familiar enough with binja lifting (or in fact with the MSP430) to be sure which part the issue is in, but it definitely seems wrong! (I encountered this first in real code, where a static binary-search over different possible values was nonsensical, as comparisons were against numbers that would be illegal at that point in the program flow).

**Comment by joshwatson** [comment]
Thanks for the report, sorry I only saw it now! This is fixed now
