### ISSUE TITLE
port to binja plugin API

### ISSUE THREAD

**Issue by lucasduffey** [joshwatson/binaryninja-msp430#3]
# relevant pull requests
- rename to `__init__.py`: https://github.com/joshwatson/binaryninja-msp430/pull/1
- create plugin.json: https://github.com/joshwatson/binaryninja-msp430/pull/2

**Comment by joshwatson** [comment]
First PR accepted, second PR closed. The plugin is now accepted into the official binaryninja-plugins repo!
