### ISSUE TITLE
DefaultCallingConvention attributes problem

### ISSUE THREAD

**Issue by EvanMcBroom** [joshwatson/binaryninja-msp430#8]
### <h3>Binary Ninja version</h3>
`1.1.931-dev Personal`

### <h3>Log error</h3>
```
Traceback (most recent call last):
  File "~/Library/Application Support/Binary Ninja/plugins/msp430/__init__.py", line 1089, in <module>
    arch.register_calling_convention(DefaultCallingConvention(arch))
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/callingconvention.py", line 52, in __init__
    raise ValueError("Must specify either handle or architecture and name")
ValueError: Must specify either handle or architecture and name
Python plugin 'msp430' could not be loaded
```

I believe that it is intended for the object [DefaultCallingConvention(arch)](https://github.com/joshwatson/binaryninja-msp430/blob/f49987155156c4e4d8fd3c36e0e0fcda4b97f2bf/__init__.py#L1089) to have the attributes __architecture__ and __name__ set to __Architecture['msp430']__ and __'default'__, but [arch.register_calling_convention()](https://github.com/joshwatson/binaryninja-msp430/blob/f49987155156c4e4d8fd3c36e0e0fcda4b97f2bf/__init__.py#L1089) does not recognize them to be set.

**Comment by joshwatson** [comment]
Ugh, yes, I fixed this and then forgot to push it. It should be fixed in master now.
