### ISSUE TITLE
`branch_target` is not properly calculated

### ISSUE THREAD

**Issue by jiva** [joshwatson/binaryninja-msp430#9]
Binary Ninja version: 1.1.989 Personal
Microcorruption level: Chernobyl

On address `0x4bbc`, Microcorruption's debugger decodes the instruction as `4bbc: 923c  jmp #0x4ce2 <run+0x17c>` and Binary Ninja decodes the instruction as `00004bbc 923c  jmp 0x44e2L`, which off by 0x800. This is being caused by the if-statement [line 984](https://github.com/joshwatson/binaryninja-msp430/blob/4a27cda38c8b00a9aadbc8916e40e88f2adfa553/__init__.py#L984) (which, according to the comment, checks if the offset is negative). I'm not entirely sure of the correct fix for this issue, but I suspect the condition needs to be changed.

**Comment by joshwatson** [comment]
Looking at that, I’m honestly not sure what I was thinking at the time. I’ll try to fix it tonight if I get a chance
